package io.delightlabs.aegis.crypt.hash

import org.junit.Assert
import org.junit.Test

class Blake2bUnitTest {
    @OptIn(ExperimentalUnsignedTypes::class)
    @Test
    fun testBlake2b256() {
        val res = blake2b(32, byteArrayOf(1))
        Assert.assertEquals(
            ubyteArrayOf(
                57.toUByte(),
                186.toUByte(),
                166.toUByte(),
                236.toUByte(),
                19.toUByte(),
                146.toUByte(),
                235.toUByte(),
                145.toUByte(),
                2.toUByte(),
                4.toUByte(),
                173.toUByte(),
                250.toUByte(),
                198.toUByte(),
                60.toUByte(),
                189.toUByte(),
                133.toUByte(),
                97.toUByte(),
                194.toUByte(),
                167.toUByte(),
                140.toUByte(),
                8.toUByte(),
                52.toUByte(),
                217.toUByte(),
                162.toUByte(),
                254.toUByte(),
                94.toUByte(),
                84.toUByte(),
                155.toUByte(),
                188.toUByte(),
                128.toUByte(),
                189.toUByte(),
                95.toUByte()
            ).contentToString(),
            res.toUByteArray().contentToString()
        )
    }

    @OptIn(ExperimentalUnsignedTypes::class)
    @Test
    fun testBlake2b128() {
        val res = blake2b(16, byteArrayOf(1))
        Assert.assertEquals(
            ubyteArrayOf(
                250.toUByte(),
                15.toUByte(),
                82.toUByte(),
                78.toUByte(),
                233.toUByte(),
                20.toUByte(),
                107.toUByte(),
                127.toUByte(),
                59.toUByte(),
                79.toUByte(),
                144.toUByte(),
                73.toUByte(),
                148.toUByte(),
                201.toUByte(),
                90.toUByte(),
                60.toUByte()
            ).contentToString(),
            res.toUByteArray().contentToString()
        )
    }

    @OptIn(ExperimentalUnsignedTypes::class)
    @Test
    fun testBlake2b512() {
        val res = blake2b(64, byteArrayOf(1,2,3,4,5,6))
        Assert.assertEquals(
            ubyteArrayOf(
                121.toUByte(),
                168.toUByte(),
                151.toUByte(),
                124.toUByte(),
                202.toUByte(),
                162.toUByte(),
                163.toUByte(),
                247.toUByte(),
                183.toUByte(),
                176.toUByte(),
                17.toUByte(),
                1.toUByte(),
                179.toUByte(),
                207.toUByte(),
                213.toUByte(),
                9.toUByte(),
                157.toUByte(),
                151.toUByte(),
                156.toUByte(),
                171.toUByte(),
                24.toUByte(),
                248.toUByte(),
                19.toUByte(),
                196.toUByte(),
                89.toUByte(),
                176.toUByte(),
                177.toUByte(),
                181.toUByte(),
                216.toUByte(),
                50.toUByte(),
                182.toUByte(),
                39.toUByte(),
                234.toUByte(),
                108.toUByte(),
                12.toUByte(),
                135.toUByte(),
                191.toUByte(),
                27.toUByte(),
                249.toUByte(),
                171.toUByte(),
                130.toUByte(),
                116.toUByte(),
                71.toUByte(),
                152.toUByte(),
                153.toUByte(),
                251.toUByte(),
                243.toUByte(),
                125.toUByte(),
                189.toUByte(),
                107.toUByte(),
                243.toUByte(),
                241.toUByte(),
                49.toUByte(),
                100.toUByte(),
                49.toUByte(),
                137.toUByte(),
                41.toUByte(),
                241.toUByte(),
                36.toUByte(),
                248.toUByte(),
                162.toUByte(),
                32.toUByte(),
                118.toUByte(),
                93.toUByte()
            ).contentToString(),
            res.toUByteArray().contentToString()
        )
    }
}